services:
  postgres:
    image: postgres
    container_name: blog-pg
    ports:
      - "${DB_PORT}:5432"
    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U ${POSTGRES_USER} -d ${POSTGRES_DB}" ]
      interval: 3s
      timeout: 5s
      retries: 5
    volumes:
      - pgdata:/var/lib/postgresql/data

  api:
    build: .
    container_name: blog-api
    ports:
      - "${PORT}:${PORT}"
    environment:
      DATABASE_URL: postgres://${DB_USER}:${DB_PASSWORD}@postgres:5432/blog?sslmode=disable
      PORT: ${PORT}
      API_KEY: ${API_KEY}
    depends_on:
      postgres:
        condition: service_healthy

volumes:
  pgdata:
