services:
  postgres:
    image: postgres
    container_name: blog-postgres
    ports:
      - "5432:5432"
    environment:
      POSTGRES_DB: blog
      POSTGRES_USER: blogadmin
      POSTGRES_PASSWORD: blogadmin
    volumes:
      - pgdata:/var/lib/postgresql/data

volumes:
  pgdata:
