services:
  postgres:
    image: postgres
    container_name: blog-pg
    ports:
      - "5432:5432"
    environment:
      POSTGRES_DB: blog
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin
    volumes:
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
      - pgdata:/var/lib/postgresql/data


  api:
    build: .
    container_name: blog-api
    ports:
      - "8080:8080"
    environment:
      - DATABASE_URL=postgres://admin:admin@postgres:5432/blog
      - PORT=8080
    depends_on:
      - postgres

volumes:
  pgdata:
