services:
  postgres:
    image: postgres
    container_name: blog-pg
    ports:
      - "5432:5432"
    environment:
      POSTGRES_DB: blog
      POSTGRES_USER: blogadmin
      POSTGRES_PASSWORD: blogadmin
    volumes:
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
      - pgdata:/var/lib/postgresql/data
volumes:
  pgdata:
