### POST Users
POST http://localhost:8080/users
Content-Type: application/json

{
  "username": "",
  "email":"alice4@example.com"
}

### GET Users
GET http://localhost:8080/users

### GET User By ID
GET http://localhost:8080/users/101

### UPDATE User By ID
PATCH http://localhost:8080/users/234

### DELETE User By ID
DELETE http://localhost:8080/users/345