

### GET Users
GET http://localhost:8080/api/v1/users

### GET User By ID
GET http://localhost:8080/api/v1/users/112

### POST Users
POST http://localhost:8080/api/v1/users
Content-Type: application/json

{
  "username": "bloggertest",
  "email": "bloggertest@example.com"
}

### UPDATE User By ID
PATCH http://localhost:8080/api/v1/users/7173c005-9796-44e3-8cc1-36efd35a2807
Content-Type: application/json

{
  "email": "blogger01@example.com"
}

### DELETE User By ID
DELETE http://localhost:8080/api/v1/users/101