

### GET Users
GET http://localhost:8080/api/v1/users

### GET User By ID
GET http://localhost:8080/api/v1/users/112

### POST Users
POST http://localhost:8080/api/v1/users
Content-Type: application/json

{
  "username": "12",
  "email": "bloggertesthlkghjg@example.com"
}

### UPDATE User By ID
PATCH http://localhost:8080/api/v1/users/58e631f4-3ea8-4a9f-b97e-aa040a82ea23
Content-Type: application/json

{
  "username": "blogger01"
}

### DELETE User By ID
DELETE http://localhost:8080/api/v1/users/101