name: Deploy to Hetzner

on:
  workflow_run:
    workflows: [ "Go" ]
    types: [ completed ]

jobs:
  deploy:
    if: ${{ github.event.workflow_run.conclusion == 'success' &&
      github.event.workflow_run.head_branch == 'main' }}
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      
      # Download the docs artifact from the build job
    - name: Download Swagger docs
      uses: actions/download-artifact@v4
      with:
        name: swagger-docs
        path: docs

    - name: Create .env file from secrets and variables
      run: |
        cat > .env <<EOF
        # DB and app settings
        DB_USER=${{ vars.DB_USER }}
        DB_PASSWORD=${{ secrets.DB_PASSWORD }}
        DB_NAME=${{ vars.DB_NAME }}
        DB_PORT=${{ vars.DB_PORT }}
        DB_HOST=${{ vars.DB_HOST }}
        PORT=${{ vars.PORT }}
        
        # API key
        API_KEY=${{ secrets.API_KEY }}
        
        # Postgres container env
        POSTGRES_USER=${{ vars.DB_USER }}
        POSTGRES_PASSWORD=${{ secrets.DB_PASSWORD }}
        POSTGRES_DB=${{ vars.DB_NAME }}
        EOF

    - name: Add SSH key for deploy
      uses: webfactory/ssh-agent@v0.8.0
      with:
        ssh-private-key: ${{ secrets.HETZNER_SSH_KEY }}

    - name: Copy compose and env files to server
      run: |
        rsync -avz -e 'ssh -o StrictHostKeyChecking=no' docker-compose.yml .env root@${{ secrets.HETZNER_HOST }}:/root/app/

    - name: Deploy with Docker Compose
      run: |
        ssh -o StrictHostKeyChecking=no root@${{ secrets.HETZNER_HOST }} '
          cd /root/app &&
          docker compose pull &&
          docker compose up -d
        '