# This workflow will build a golang project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-go

name: Go

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4

    - name: Set up Go
      uses: actions/setup-go@v4
      with:
        go-version: '1.24'

    - name: Build
      run: go build -v ./...

    - name: Start services with Docker Compose
      run: docker-compose up -d

    - name: Wait for Postgres
      run: |
        for i in {1..20}; do
        pg_isready -h 127.0.0.1 -p 5432 && break
        sleep 1
        done

    - name: Test
      run: go test -v ./...
