# This workflow will build a golang project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-go

name: Go

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4

    - name: Set up Go
      uses: actions/setup-go@v4
      with:
        go-version: '1.24'

    - name: Build
      run: go build -v ./...

    - name: Test
      run: go test -v ./...

      #change host to match prod url
    - name: Install swag CLI
      run: go install github.com/swaggo/swag/cmd/swag@latest

    - name: Add Go bin to PATH
      run: echo "$(go env GOPATH)/bin" >> $GITHUB_PATH

    - name: Set Swagger host to prod and generate docs
      run: |
        sed -i 's|@host .*|@host blog.pandahawk.dev|' main.go
        swag init

      # Upload the docs folder as an artifact for the deploy job
    - name: Upload Swagger docs
      uses: actions/upload-artifact@v4
      with:
        name: swagger-docs
        path: docs/

      # ---- Only build/push Docker image for main branch ----
    - name: Log in to Docker Hub
      if: github.ref == 'refs/heads/main'
      uses: docker/login-action@v3
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_TOKEN }}

    - name: Build and push Docker image
      if: github.ref == 'refs/heads/main'
      uses: docker/build-push-action@v5
      with:
        context: .
        push: true
        tags: pandahawk251/myapps:blog-api-latest
